DROP DATABASE booklister_db;
CREATE DATABASE IF NOT EXISTS booklister_db;

USE booklister_db;

DROP TABLE IF EXISTS ads;
DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS users (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    username VARCHAR(255) UNIQUE NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS genres (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    genre VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS admins (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    users_id INT UNSIGNED NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (users_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS ads (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    users_id INT UNSIGNED NOT NULL,
    genres_id INT UNSIGNED NOT NULL,
    title VARCHAR(255) NOT NULL,
    price DOUBLE UNSIGNED NOT NULL,
    conditions VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    summary TEXT NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (users_id) REFERENCES users(id),
    FOREIGN KEY (genres_id) REFERENCES genres(id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS user_images (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    genre VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);